[package]
name = "katna-ui"
description = "Shared GPUI components for Katna apps."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
katna-core.workspace = true

[lints]
workspace = true
