#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Writes the list of libraries Katna uses, from `cargo metadata`:
#   docs/credits.json  for the app's About dialog
#   CREDITS.md         for people, linked from the README
# Lists every crate a workspace crate depends on directly (normal and build
# dependencies on Linux), including the patched GPUI copies in vendor/.
# With --check, fails if either file is out of date instead of writing it.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
json_out="$root/docs/credits.json"
md_out="$root/CREDITS.md"

metadata="$(cargo metadata --manifest-path "$root/Cargo.toml" --format-version 1 \
    --locked --filter-platform x86_64-unknown-linux-gnu)"

json="$(jq '
    .workspace_members as $members
    | (.packages | map({key: .id, value: .}) | from_entries) as $pkgs
    | [ .resolve.nodes[]
        | select(.id as $id | $members | index($id))
        | .deps[]
        | select(any(.dep_kinds[]; .kind == null or .kind == "build"))
        | .pkg ]
    | unique
    | map(select(. as $id | $members | index($id) | not) | $pkgs[.])
    | map(
        (.repository // "" | sub("\\.git$"; "") | sub("/$"; "")) as $repo
        | ([.authors[] | sub("\\s*<[^>]*>"; "") | select(length > 0)] | unique) as $authors
        | {
            name,
            version,
            description: ((.description // "") | gsub("\\s+"; " ") | sub("^ "; "") | sub(" $"; "")),
            license: (.license // "see repository"),
            authors: (if ($authors | length) > 0 then $authors
                      else [$repo | capture("github\\.com/(?<owner>[^/]+)").owner // empty]
                      end),
            repository: (if $repo != "" then $repo else "https://crates.io/crates/\(.name)" end)
          })
    | unique_by(.name)
    | {generated_by: "ci/gen-credits.sh", crates: .}
' <<<"$metadata")"

# Every crate that is not ours and ends up in a build (not only in tests), to
# say how many come in indirectly.
all="$(jq '
    .workspace_members as $members
    | (.resolve.nodes
       | map({key: .id, value: [.deps[] | select(any(.dep_kinds[]; .kind == null or .kind == "build")) | .pkg]})
       | from_entries) as $graph
    | def reach: . as $seen
        | ($seen + [$seen[] as $id | $graph[$id][]] | unique) as $next
        | if ($next | length) == ($seen | length) then $seen else $next | reach end;
    $members | unique | reach
    | map(select(. as $id | $members | index($id) | not)) | length
' <<<"$metadata")"

md="$(jq -r --argjson all "$all" '
    def cell: gsub("\\|"; "\\|");
    "<!-- SPDX-License-Identifier: GPL-3.0-or-later -->",
    "<!-- Generated by ci/gen-credits.sh from Cargo.lock. Do not edit by hand. -->",
    "",
    "# Credits",
    "",
    "Katna stands on the work of these open-source libraries and the people",
    "who make them. Thank you. This is every crate Katna uses directly; they",
    "bring in \($all - (.crates | length)) more of their own. Each keeps its own license.",
    "",
    "| Library | By | License | What it does |",
    "|---|---|---|---|",
    (.crates[] | "| [\(.name)](\(.repository)) \(.version) | \(.authors | join(", ") | cell) | \(.license | cell) | \(.description | cell) |")
' <<<"$json")"

if [[ "${1:-}" == "--check" ]]; then
    if [[ "$json" != "$(cat "$json_out")" || "$md" != "$(cat "$md_out")" ]]; then
        echo "docs/credits.json or CREDITS.md is out of date: run ci/gen-credits.sh" >&2
        exit 1
    fi
    exit 0
fi

printf '%s\n' "$json" >"$json_out"
printf '%s\n' "$md" >"$md_out"
