[package]
name = "katnactl"
description = "Command-line client for the Katna daemon."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
katna-core.workspace = true
katna-dbus.workspace = true
katna-store.workspace = true
futures-lite.workspace = true
rpassword.workspace = true
zbus.workspace = true

[lints]
workspace = true
